const button = document.getElementById("button");
const name = document.querySelector(".pokemon-text-container");
const gif = document.querySelector(".pokemon-gif-container");
const info = document.querySelector(".pokemon-info");
const evolution = document.querySelector(".pokemon-evolution");
const sound = document.getElementById("sound-container");
const searchButton = document.querySelector(".input-search-button");
const searchInput = document.querySelector(".input-search");


const nt = "./media/nt.gif";
const x = "./media/x.gif";
const buscandopokemon = "https://i.makeagif.com/media/8-21-2016/V1OnWi.gif";

//in the array we define the characteristics that the pokemon will have('ev' = 'evolution')
const pokemonList = [
  {
      
  }, 
  {
      name: "Bulbasaur",
      gif : "https://media.tenor.com/JYtlflYYs9wAAAAM/bulbasaur-nodding.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/ivysaur.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/venusaur.gif",
  },
  {
      name: "Ivysaur",
      gif : "https://gifs.eco.br/wp-content/uploads/2022/04/gifs-do-ivysaur-0.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/ivysaur.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/venusaur.gif",
  },
  {
      name: "Venusaur",
      gif : "https://gifs.eco.br/wp-content/uploads/2022/04/gifs-do-venusaur-1.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/ivysaur.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/venusaur.gif",
  },
  {
      name: "Charmander",
      gif : "https://media.tenor.com/qIhgj8cLz9UAAAAM/charmander-charmander-pokemon.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/charmander.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/charmeleon.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/charizard.gif",
  },
  {
      name: "Charmeleon",
      gif : "http://24.media.tumblr.com/189f7d304c9fab589f89e5cd65a109ea/tumblr_mr8jriFfDA1qhd8sao1_500.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/charmander.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/charmeleon.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/charizard.gif",
  },
  {
      name: "Charizard",
      gif : "http://31.media.tumblr.com/d8865f0b5c3471c70f29afbc71176236/tumblr_ml4msevS3m1r3ifxzo1_500.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/charmander.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/charmeleon.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/charizard.gif",
  },
  {
      name: "Squirtle",
      gif : "https://media.tenor.com/Ken3eHIfWnAAAAAM/pokemon-squirtle.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/squirtle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/wartortle.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/blastoise.gif",
  },
  {
      name: "Wartortle",
      gif : "https://i.pinimg.com/originals/21/36/4d/21364d959852b93ffec98ea9c6bc77b5.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/squirtle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/wartortle.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/blastoise.gif",
  },
  {
      name: "Blastoise",
      gif : "https://media.tenor.com/rLFfSIKDXGoAAAAM/yo-you-good-lmao-yeah-thanks.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/squirtle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/wartortle.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/blastoise.gif",
  },
  {
      name: "Caterpie",
      gif : "https://media.tenor.com/rBRu9Y6AJMMAAAAC/caterpie-caterpillar.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/caterpie.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/metapod.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/butterfree.gif",
  },
  {
      name: "Metapod",
      gif : "https://sm.mashable.com/mashable_sea/photo/default/9c977814f026a9cbaa86df7cb0c33af6f0df8060-00_67jf.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/caterpie.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/metapod.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/butterfree.gif",
  },
  {
      name: "Butterfree",
      gif : "https://media.tenor.com/A8kgsqhltPIAAAAC/pokemon-pokemon-butterfree.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/caterpie.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/metapod.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/butterfree.gif",
  },
  {
      name: "weedle",
      gif : "https://media.tenor.com/rs3U38Pu2XsAAAAM/weedle-pokemon.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/weedle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kakuna.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/beedrill.gif",
  },
  {
      name: "kakuna",
      gif : "https://media.tenor.com/261fjYU3-uoAAAAC/kakuna-pokemon.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/weedle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kakuna.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/beedrill.gif",
  },
  {
      name: "beedrill",
      gif : "https://thumbs.gfycat.com/BlueInstructiveDiplodocus-size_restricted.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/weedle.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kakuna.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/beedrill.gif",
  },
  {
      name: "pidgey",
      gif : "https://media.tenor.com/9y3ql3fTKMMAAAAC/pidgey-cute.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/pidgey.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/pidgeot.gif",
  },
  {
      name: "pidgeotto",
      gif : "https://media.tenor.com/bHL9O-KFgoQAAAAC/pidgeotto-pokemon.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/pidgey.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/pidgeot.gif",
  },
  {
      name: "pidgeot",
      gif : "https://media.tenor.com/TS12692KzXcAAAAC/pidgeot-pigeon.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/pidgey.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/pidgeot.gif",
  },
  {
      name: "Rattata",
      gif : "https://media.tenor.com/JI2kGjoQ3_MAAAAC/pokemon-rattata.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/rattata.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/raticate.gif",
      ev3: nt,
  },
  {
      name: "raticate",
      gif : "https://pa1.narvii.com/6159/10fc0e6ab91d851fa9f223f78139c6a280a9679b_hq.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/rattata.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/raticate.gif",
      ev3: nt,
  },
  {
      name: "Spearow",
      gif : "http://24.media.tumblr.com/9701e3cf6a58fce229a5136353279cb7/tumblr_mn61rvvdqV1rjp53to1_400.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/spearow.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/fearow.gif",
      ev3: nt,
  },
  {
      name: "Fearow",
      gif : "https://i.gifer.com/origin/aa/aa569228c585a59f0acd355ee4a3fb3d.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/spearow.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/fearow.gif",
      ev3: nt,
  },
  {
      name: "Ekans",
      gif : "https://media.tenor.com/Oz7Uz-ZMiToAAAAC/ekans-pokemon.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/ekans.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/arbok.gif",
      ev3: nt,
  },
  {
      name: "Arbok",
      gif : "https://media.tenor.com/-oBJrci79jMAAAAC/pokemon-arbok.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/ekans.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/arbok.gif",
      ev3: nt,
  },
  {
      name: "Pikachu",
      gif : "https://i.pinimg.com/originals/8a/81/ec/8a81ecd8fdd266b3221da325875c0ea8.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/pikachu.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/raichu.gif",
      ev3: nt,
  },
  {
      name: "raichu",
      gif : "https://media.tenor.com/Nu0eEzo0nOMAAAAC/raichu-raichu-pokemon.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/pikachu.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/raichu.gif",
      ev3: nt,
  },
  {
      name: "Sandshrew",
      gif : "https://i.pinimg.com/originals/ad/7e/82/ad7e82073c11a10bb65b8c11039af0e0.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/sandshrew.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/sandslash.gif",
      ev3: nt,
  },
  {
      name: "sandslash",
      gif : "https://media.tenor.com/6w0Lwo9COFIAAAAC/sandslash-spin.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/sandshrew.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/sandslash.gif",
      ev3: nt,
  },
  {
      name: "Nidoran♀",
      gif : "https://i.pinimg.com/originals/f3/c7/16/f3c716e4a26f3c7204fdc5e00666431a.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorina.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif",
  },
  {
      name: "nidorina",
      gif : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCEUCWG2XWgl7NnaJTwjwd-81s5LQov8dSrQTHHJDKQUw97k5U6mYtLQl0O63fdep1dgM&usqp=CAU",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorina.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif",
  },
  {
      name: "nidoqueen",
      gif : "http://pa1.narvii.com/6788/0ea4ebceae39a557afa7c42b286ce0e8d6a2fff5_00.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/t.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorina.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif",
  },
  {
      name: "Nidoran♂",
      gif : "https://i.gifer.com/origin/f5/f509c95932182166df9a04f25d0c4e11.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorino.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoking.gif",
  },
  {
      name: "nidorino",
      gif : "http://pa1.narvii.com/6273/fd71cf4398f8420a4260d080e46b76f2bb0ab7d6_00.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorino.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoking.gif",
  },
  {
      name: "nidoking",
      gif : "https://media.tenor.com/NyxZuUTU6EMAAAAC/nidoking-pok%C3%A9mon-nidoking.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/t.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/nidorino.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/nidoking.gif",
  },
  {
      name: "Clefairy",
      gif : "https://thumbs.gfycat.com/CostlyDifficultArabianwildcat-max-1mb.gif",
      type1: "./media/type/h.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/clefairy.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/clefable.gif",
      ev3: nt,
  },
  {
      name: "clefable",
      gif : "https://media4.giphy.com/media/TJ2eWMiqkOqQg/giphy.gif",
      type1: "./media/type/h.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/clefairy.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/clefable.gif",
      ev3: nt,
  },
  {
      name: "Vulpix",
      gif : "https://i.gifer.com/origin/39/3930893994563dc851d3c4d35d8a1457.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/vulpix.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/ninetales.gif",
      ev3: nt,
  },
  {
      name: "ninetales",
      gif : "https://media.tenor.com/O8_ehlW_iYsAAAAC/ninetales.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/vulpix.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/ninetales.gif",
      ev3: nt,
  },
  {
      name: "Jigglypuff",
      gif : "https://media3.giphy.com/media/EKDSLoPz0yLVC/giphy.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/h.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/jigglypuff.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/wigglytuff.gif",
      ev3: nt,
  },
  {
      name: "wigglytuff",
      gif : "https://i.pinimg.com/originals/b4/9f/a1/b49fa10bee8e79905f0487a87110b910.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/h.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/jigglypuff.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/wigglytuff.gif",
      ev3: nt,
  },
  {
      name: "Zubat",
      gif : "https://i.gifer.com/8Xk8.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/zubat.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/golbat.gif",
      ev3: nt,
  },
  {
      name: "golbat",
      gif : "https://media.tenor.com/iGbkGP-vYu8AAAAC/golbat-shadow-ball.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/zubat.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/golbat.gif",
      ev3: nt,
  },
  {
      name: "Oddish",
      gif : "https://media.tenor.com/HFTgIsLNWGUAAAAC/oddish-pokemon.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/oddish.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/gloom.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/vileplume.gif",
  },
  {
      name: "gloom",
      gif : "https://media.tenor.com/NZykCWd-4wEAAAAd/gloom-pokemon.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/oddish.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/gloom.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/vileplume.gif",
  },
  {
      name: "vileplume",
      gif : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfnVPW7ZP4aYFVo5w9HHiVYLmISga_yHfWcMvAWYSThKMP1DJ70IXlklnOUtmzJgE6_j0&usqp=CAU",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/oddish.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/gloom.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/vileplume.gif",
  },
  {
      name: "Paras",
      gif : "https://pa1.narvii.com/6186/ff24a1b61d5b1b19484c73b9d6cbd44924a1297a_hq.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/p.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/paras.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/parasect.gif",
      ev3: nt,
  },
  {
      name: "parasect",
      gif : "https://pa1.narvii.com/5822/6ad4b2d43dda6af8e1630536a1bb51bd544bd1f9_hq.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/p.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/paras.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/parasect.gif",
      ev3: nt,
  },
  {
      name: "venonat",
      gif : "https://media.tenor.com/gPuwrxxBZ0sAAAAd/venonat-pokemon.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/venonat.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/venomoth.gif",
      ev3: nt,
  },
  {
      name: "venomoth",
      gif : "https://64.media.tumblr.com/89f41419b1055d871159d5c180bb4cfc/tumblr_ot8kq4H5OR1vpbs3jo1_640.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/venonat.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/venomoth.gif",
      ev3: nt,
  },
  {
      name: "Diglett",
      gif : "https://media.tenor.com/wuw4q53RMPQAAAAC/pokemon-diglett.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/diglett.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dugtrio.gif",
      ev3: nt,
  },
  {
      name: "dugtrio",
      gif : "https://i.pinimg.com/originals/c5/e3/c4/c5e3c49a927761800b0e2e0dc40ce6b0.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/diglett.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dugtrio.gif",
      ev3: nt,
  },
  {
      name: "Meowth",
      gif : "https://i.pinimg.com/originals/d0/62/b1/d062b1147fc2bd3ae3c9db382f3932f0.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/meowth.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/persian.gif",
      ev3: nt,
  },
  {
      name: "persian",
      gif : "https://media.tenor.com/98ZLi9DJPBcAAAAC/pokemon-persian.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/meowth.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/persian.gif",
      ev3: nt,
  },
  {
      name: "psyduck",
      gif : "https://media.tenor.com/5rbtjevzC1cAAAAC/pokemon-psyduck.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/psyduck.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/golduck.gif",
      ev3: nt,
  },
  {
      name: "golduck",
      gif : "https://i.gifer.com/C7h8.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/psyduck.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/golduck.gif",
      ev3: nt,
  },
  {
      name: "Mankey",
      gif : "https://64.media.tumblr.com/32dec5fccabad564e61a3bab24c028eb/tumblr_o3hg2g7vfI1rnrreio1_640.gifv",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/mankey.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/primeape.gif",
      ev3: nt,
  },
  {
      name: "primeape",
      gif : "https://64.media.tumblr.com/ac77943c9db74082a66937e7c3a4ae11/tumblr_og6ykea52k1tgjlm2o1_500.gif",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/mankey.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/primeape.gif",
      ev3: nt,
  },
  {
      name: "Growlithe",
      gif : "https://thumbs.gfycat.com/AcidicAshamedBooby-size_restricted.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/growlithe.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/arcanine.gif",
      ev3: nt,
  },
  {
      name: "arcanine",
      gif : "https://i.pinimg.com/originals/be/90/c2/be90c2f5187281a0f7179c40c0211619.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/growlithe.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/arcanine.gif",
      ev3: nt,
  },
  {
      name: "Poliwag",
      gif : "https://media.tenor.com/DSTbBQBybw8AAAAC/pokemon-poliwag.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/poliwag.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/poliwrath.gif",
  },
  {
      name: "poliwhirl",
      gif : "https://media.tenor.com/U3-bM1OitDEAAAAC/pokemon-poliwhirl.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/poliwag.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/poliwrath.gif",
  },
  {
      name: "poliwrath",
      gif : "https://media.tenor.com/op6YDu5-kl0AAAAC/pokemon-poliwrath.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/l.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/poliwag.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/poliwrath.gif",
  },
  {
      name: "Abra",
      gif : "https://media.tenor.com/FQaqgLa0EJ0AAAAC/pokemon-run.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/abra.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kadabra.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/alakazam.gif",
  },
  {
      name: "kadabra",
      gif : "https://24.media.tumblr.com/8cb2f110099499bb8c2b6ae459781eec/tumblr_mi3awaRJAo1r922jeo1_500.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/abra.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kadabra.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/alakazam.gif",
  },
  {
      name: "alakazam",
      gif : "https://media.tenor.com/vuJ4ABnFW8oAAAAC/pokemon-spoon.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/abra.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kadabra.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/alakazam.gif",
  },
  {
      name: "Machop",
      gif : "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d7ebf501-d835-4c15-9782-1332ea9fb086/de2sifi-5c4a637b-b428-42ce-afd7-b225fe0da831.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2Q3ZWJmNTAxLWQ4MzUtNGMxNS05NzgyLTEzMzJlYTlmYjA4NlwvZGUyc2lmaS01YzRhNjM3Yi1iNDI4LTQyY2UtYWZkNy1iMjI1ZmUwZGE4MzEuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.m0B5QI6Tc1v8i_vYqNf9dpkFB86oFYGjkOf46l42q8c",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/machop.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/machoke.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/machamp.gif",
  },
  {
      name: "machoke",
      gif : "https://thumbs.gfycat.com/BitterSmugAngelfish-size_restricted.gif",
      type1: "./media/type/l.png",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/machop.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/machoke.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/machamp.gif",
  },
  {
      name: "machamp",
      gif : "https://64.media.tumblr.com/2f4afc7f236e8ad21c27b72a44e961cc/tumblr_nsn80eKs4N1tgjlm2o1_500.gif",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/machop.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/machoke.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/machamp.gif",
  },
  {
      name: "Bellsprout",
      gif : "https://i.pinimg.com/originals/8f/2f/d4/8f2fd4e6df839a342b8612c7c8b851d7.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bellsprout.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/weepinbell.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/victreebel.gif",
  },
  {
      name: "weepinbell",
      gif : "https://64.media.tumblr.com/e7d646549b9ea800b85238cc87eb7bdb/25bee2a60db72dc2-f9/s640x960/922c774fd6cd33058031411a9eaab929f6e7d792.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bellsprout.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/weepinbell.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/victreebel.gif",
  },
  {
      name: "victreebel",
      gif : "https://64.media.tumblr.com/bb96b3c20a3855612774c9fffda4ad16/tumblr_nd058dLkAM1tqptlzo1_500.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/bellsprout.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/weepinbell.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/victreebel.gif",
  },
  {
      name: "Tentacool",
      gif : "https://64.media.tumblr.com/4346aa7491504bebc7818db4d36462f1/tumblr_mgwjappDd31qd87hlo1_500.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/tentacool.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/tentacruel.gif",
      ev3: nt,
  },
  {
      name: "tentacruel",
      gif : "https://media.tenor.com/X-m58xs73uUAAAAC/tentacruel-pokemon.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/tentacool.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/tentacruel.gif",
      ev3: nt,
  },
  {
      name: "Geodude",
      gif : "https://media0.giphy.com/media/bBbqh3SLbKAcE/giphy.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/t.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/geodude.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/graveler.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/golem.gif",
  },
  {
      name: "graveler",
      gif : "./media/graveler.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/t.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/geodude.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/graveler.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/golem.gif",
  },
  {
      name: "golem",
      gif : "https://i.gifer.com/9FeC.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/t.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/geodude.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/graveler.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/golem.gif",
  },
  {
      name: "Ponyta",
      gif : "https://i.gifer.com/origin/7d/7d1ea43b523687bf5603ff60af49c69f.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/ponyta.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/rapidash.gif",
      ev3: nt,
  },
  {
      name: "rapidash",
      gif : "https://media.tenor.com/9PBJqh_8CWkAAAAC/rapidash-pokemon.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/ponyta.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/rapidash.gif",
      ev3: nt,
  },
  {
      name: "Slowpoke",
      gif : "https://media.tenor.com/MTnIZZmt72sAAAAC/slowpoke-pokemon.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/ps.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/slowpoke.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/slowbro.gif",
      ev3: nt,
  },
  {
      name: "Slowbro",
      gif : "http://pa1.narvii.com/6316/898401ca0063e6a30835ba3d476b5f15eba1a32a_00.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/ps.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/slowpoke.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/slowbro.gif",
      ev3: nt,
  },
  {
      name: "Magnemite",
      gif : "https://pa1.narvii.com/6377/0b1cc3354fcc2fddb875bd05940223b866d61e05_hq.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/ac.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/magnemite.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/magneton.gif",
      ev3:  nt,
  },
  {
      name: "magneton",
      gif : "https://64.media.tumblr.com/15e328ddbc3a3cf015c1d7b4bd8fdd65/tumblr_mnohunQzG61qhd8sao1_500.gifv",
      type1: "./media/type/e.png",
      type2: "./media/type/ac.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/magnemite.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/magneton.gif",
      ev3:  nt,
  },
  {
      name: "Farfetch'd",
      gif : "https://i.pinimg.com/originals/aa/dc/bb/aadcbbc32d86849f9dde362bb0d1f7f8.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "doduo",
      gif : "http://pa1.narvii.com/5785/ea3d858e3d339198b79ffaf14d3782bb0fee29c4_hq.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/doduo.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dodrio.gif",
      ev3: nt,
  },
  {
      name: "dodrio",
      gif : "https://pa1.narvii.com/5873/91b6e41486989f6cd9789bf93d13ba59371d64f7_hq.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/doduo.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dodrio.gif",
      ev3: nt,
  },
  {
      name: "Seel",
      gif : "https://pa1.narvii.com/5987/4ae53939ce2b15d9d1380da297c6e939ae29a01c_hq.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/seel.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dewgong.gif",
      ev3: nt,
  },
  {
      name: "dewgong",
      gif : "https://31.media.tumblr.com/318118a6a3bca66fafa1987dc7279e23/tumblr_mjtufaSfx01rp6axuo1_r1_500.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/hi.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/seel.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dewgong.gif",
      ev3: nt,
  },
  {
      name: "Grimer",
      gif : "https://64.media.tumblr.com/tumblr_m5427i0I9C1qkaxaxo1_500.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/grimer.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/muk.gif",
      ev3: nt,
  },
  {
      name: "muk",
      gif : "https://media.tenor.com/yA8BrZ9KshUAAAAC/muk-pokemon.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/grimer.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/muk.gif",
      ev3: nt,
  },
  {
      name: "Shellder",
      gif : "https://media.tenor.com/LinPC1c8hoAAAAAC/shellder-haze.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/shellder.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/cloyster.gif",
      ev3: nt,
  },
  {
      name: "cloyster",
      gif : "https://64.media.tumblr.com/b089347875b869c881b927be5c7117fb/tumblr_okze5rp8YQ1s5fnj9o1_540.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/hi.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/shellder.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/cloyster.gif",
      ev3: nt,
  },
  {
      name: "Gastly",
      gif : "https://i.gifer.com/origin/f6/f6ee07b3d00b82f734b630454add16de.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/gastly.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/haunter.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/gengar.gif",
  },
  {
      name: "haunter",
      gif : "http://25.media.tumblr.com/7190fe583783c542256eb76522eb4794/tumblr_moion3v15L1qhd8sao1_500.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/gastly.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/haunter.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/gengar.gif",
  },
  {
      name: "gengar",
      gif : "https://media.tenor.com/sBX3uFWy4woAAAAC/gengar-daze.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/v.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/gastly.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/haunter.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/gengar.gif",
  },
  {
      name: "Onix",
      gif : "https://media.tenor.com/bUOPWft1ZdEAAAAC/pok%C3%A9mon-onix.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/t.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Drowzee",
      gif : "https://thumbs.gfycat.com/CheerfulDimAnhinga-size_restricted.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/drowzee.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/hypno.gif",
      ev3: nt,
  },
  {
      name: "hypno",
      gif : "https://media.tenor.com/SeNPABrnbpkAAAAC/pokemon-hypno.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/drowzee.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/hypno.gif",
      ev3: nt,
  },
  {
      name: "Krabby",
      gif : "https://media.tenor.com/kp_x95g0th0AAAAC/krabby-pokemon-bubbles-kraby-kingler.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/krabby.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kingler.gif",
      ev3: nt,
  },
  {
      name: "kingler",
      gif : "https://media.tenor.com/32t_NW33P34AAAAC/kingler-pokemon.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/krabby.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kingler.gif",
      ev3: nt,
  },
  {
      name: "Voltorb",
      gif : "https://thumbs.gfycat.com/DependableFaintFritillarybutterfly-max-1mb.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/voltorb.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/electrode.gif",
      ev3: nt,
  },
  {
      name: "electrode",
      gif : "https://i.gifer.com/8XnJ.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/voltorb.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/electrode.gif",
      ev3: nt,
  },
  {
      name: "Exeggcute",
      gif : "https://pa1.narvii.com/6163/38b9242cfb26a1fa10e44799082756b792c2d686_hq.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/ps.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/exeggcute.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/exeggutor.gif",
      ev3: nt,
  },
  {
      name: "exeggutor",
      gif : "https://i.gifer.com/origin/1f/1fb3c7b70e5359dcfd00d51f6c33527a.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/ps.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/exeggcute.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/exeggutor.gif",
      ev3: nt,
  },
  {
      name: "Cubone",
      gif : "http://24.media.tumblr.com/tumblr_mbott3v9gu1rzsfkvo1_500.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/cubone.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/marowak.gif",
      ev3: nt,
  },
  {
      name: "marowak",
      gif : "https://i.gifer.com/origin/ee/ee06c03c390c32587f07158f3b0fc045.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/cubone.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/marowak.gif",
      ev3: nt,
  },
  {
      name: "Hitmonlee",
      gif : "https://media.tenor.com/En_rjgT9YZgAAAAC/pok%C3%A9mon-hitmonlee.gif",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Hitmonchan",
      gif : "https://i.pinimg.com/originals/e8/db/0c/e8db0c42877f9c855303e5e1bbd8f056.gif",
      type1: "./media/type/l.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Lickitung",
      gif : "https://i.gifer.com/origin/a0/a0a3d6f90415bb4892fc2fa03fd88745.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Koffing",
      gif : "https://media.tenor.com/UUvLY3WqDkIAAAAC/koffing-pokemon.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/koffing.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/weezing.gif",
      ev3: nt,
  },
  {
      name: "Weezing",
      gif : "https://media.tenor.com/08AMleg9izgAAAAC/weezing-pokemon.gif",
      type1: "./media/type/v.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/koffing.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/weezing.gif",
      ev3: nt,
  },
  {
      name: "Rhyhorn",
      gif : "https://i.gifer.com/origin/7f/7f98f3a41381394dd8a41fe7c3139fee_w200.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/r.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/rhyhorn.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/rhydon.gif",
      ev3: nt,
  },
  {
      name: "rhydon",
      gif : "https://media.tenor.com/Fm15zYENMFMAAAAC/rhydon-pok%C3%A9mon-rhydon.gif",
      type1: "./media/type/t.png",
      type2: "./media/type/r.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/rhyhorn.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/rhydon.gif",
      ev3: nt,
  },
  {
      name: "Chansey",
      gif : "https://media.tenor.com/LVesZ_GILwMAAAAC/pokemon-pokemongo.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Tangela",
      gif : "https://i.pinimg.com/originals/82/c0/b6/82c0b6424f828543b8f2e08aac7ff628.gif",
      type1: "./media/type/p.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Kangaskhan",
      gif : "https://media.tenor.com/4L9ZdeYPPogAAAAC/kangaskhan-pokemon.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Horsea",
      gif : "http://pa1.narvii.com/6364/aea54484cf218d36d628d81694b55f466453779c_00.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/horsea.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/seadra.gif",
      ev3: nt,
  },
  {
      name: "seadra",
      gif : "http://24.media.tumblr.com/tumblr_mak2am6uBQ1r3ifxzo1_500.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/horsea.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/seadra.gif",
      ev3: nt,
  },
  {
      name: "Goldeen",
      gif : "http://pa1.narvii.com/5705/378ba1b051a66cd4778072a59a741566ec777444_00.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/goldeen.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/seaking.gif",
      ev3: nt,
  },
  {
      name: "seaking",
      gif : "https://24.media.tumblr.com/7f356fca7e02d909315e7b8325afd581/tumblr_mkebpdqTYV1s5mujoo1_500.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/goldeen.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/seaking.gif",
      ev3: nt,
  },
  {
      name: "Staryu",
      gif : "https://i.gifer.com/C7h7.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/staryu.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/starmie.gif",
      ev3: nt,
  },
  {
      name: "starmie",
      gif : "https://i.gifer.com/origin/85/8576b98ad0341fe0e3b1ab762086f24e.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/ps.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/staryu.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/starmie.gif",
      ev3: nt,
  },
  {
      name: "Mr. Mime	",
      gif : "http://pa1.narvii.com/6216/8bfa6520fd57b619dc691d8e460fb2ce0868502f_00.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/h.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Scyther",
      gif : "https://i.gifer.com/C8Ad.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Jynx",
      gif : "https://media.tenor.com/LlXuCHbLdfwAAAAC/pokemon-ugly.gif",
      type1: "./media/type/hi.png",
      type2: "./media/type/ps.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Electabuzz",
      gif : "https://thumbs.gfycat.com/SmoggyTerrificBighornedsheep-size_restricted.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Magmar",
      gif : "https://media.tenor.com/7UzJzVrZjqoAAAAC/magmar-pok%C3%A9mon-magmar.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Pinsir",
      gif : "https://media.tenor.com/TmSX6n0SYMoAAAAC/pinsir-pok%C3%A9mon-pinsir.gif",
      type1: "./media/type/b.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Tauros",
      gif : "https://media.tenor.com/fleK_6qPJeEAAAAC/tauros-pok%C3%A9mon-tauros.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Magikarp",
      gif : "https://media.tenor.com/LoYLZWgZo5cAAAAC/pokemon-magikarp.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/magikarp.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/gyarados.gif",
      ev3: nt,
  },
  {
      name: "gyarados",
      gif : "https://media.tenor.com/d5_PknD57wQAAAAC/pokemon-gyarados.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/magikarp.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/gyarados.gif",
      ev3: nt,
  },
  {
      name: "Lapras",
      gif : "https://media0.giphy.com/media/3vEJiMNgR6cik/giphy.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/hi.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Ditto",
      gif : "https://media.tenor.com/IA266nP_INIAAAAC/ditto-pokemon.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Eevee",
      gif : "https://media4.giphy.com/media/tDJfaLVF0gHV90lxZj/giphy.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/vaporeon.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/jolteon.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/flareon.gif",
  },
  {
      name: "Vaporeon",
      gif : "https://media.tenor.com/tT4NN73KFmoAAAAC/vaporeon-pokemon.gif",
      type1: "./media/type/a.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/eevee.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/vaporeon.gif",
      ev3: nt,
  },
  {
      name: "Jolteon",
      gif : "https://media.tenor.com/Ot8tPXmP9NkAAAAC/jolteon-pok%C3%A9mon-jolteon.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/eevee.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/jolteon.gif",
      ev3: nt,
  },
  {
      name: "Flareon",
      gif : "https://media.tenor.com/I3roL4dZDdIAAAAC/flareon-pokemon.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/eevee.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/flareon.gif",
      ev3: nt,
  },
  {
      name: "Porygon",
      gif : "https://media.tenor.com/iCfvJtBBxoIAAAAC/porygon-pokemon.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Omanyte",
      gif : "https://media.tenor.com/P1tr8EUQt_MAAAAM/helix.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/a.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/omanyte.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/omastar.gif",
      ev3: nt,
  },
  {
      name: "omastar",
      gif : "https://i.kym-cdn.com/photos/images/original/000/935/343/dbe.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/a.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/omanyte.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/omastar.gif",
      ev3: nt,
  },
  {
      name: "Kabuto",
      gif : "https://media.tenor.com/-FJvxV0F28kAAAAC/pokemon-kabuto.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/a.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/kabuto.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kabutops.gif",
      ev3: nt,
  },
  {
      name: "kabutops",
      gif : "https://media.tenor.com/0if-W6m11rAAAAAC/kabutops-pok%C3%A9mon-kabutops.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/a.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/kabuto.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/kabutops.gif",
      ev3: nt,
  },
  {
      name: "Aerodactyl",
      gif : "https://media.tenor.com/KrnQrppD8cUAAAAC/aerodactyl-pok%C3%A9mon.gif",
      type1: "./media/type/r.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Snorlax",
      gif : "https://media.tenor.com/dNDyTR73jOkAAAAM/snorlax.gif",
      type1: "./media/type/n.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Articuno",
      gif : "https://media.tenor.com/hwhT-mxGKV0AAAAC/pokemon-articuno.gif",
      type1: "./media/type/hi.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Zapdos",
      gif : "https://media.tenor.com/_Iw-Y8BCKuEAAAAC/zapdos-pokemon.gif",
      type1: "./media/type/e.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Moltres",
      gif : "https://media.tenor.com/VuI7lLFmimQAAAAC/moltres-pokemon.gif",
      type1: "./media/type/f.png",
      type2: "./media/type/vv.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Dratini",
      gif : "https://media.tenor.com/75pZWZSt490AAAAC/dratini-pokemon.gif",
      type1: "./media/type/d.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/dratini.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dragonair.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/dragonite.gif",
  },
  {
      name: "dragonair",
      gif : "https://i.gifer.com/BnIy.gif",
      type1: "./media/type/d.png",
      type2: "./media/type/nt.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/dratini.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dragonair.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/dragonite.gif",
  },
  {
      name: "dragonite",
      gif : "https://media.tenor.com/vTNxZtc3EoMAAAAC/dragonite-pokemon.gif",
      type1: "./media/type/d.png",
      type2: "./media/type/vv.png",
      ev1: "https://projectpokemon.org/images/normal-sprite/dratini.gif",
      ev2: "https://projectpokemon.org/images/normal-sprite/dragonair.gif",
      ev3: "https://projectpokemon.org/images/normal-sprite/dragonite.gif",
  },
  {
      name: "Mewtwo",
      gif : "https://media1.giphy.com/media/7ProItiELBagM/giphy.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
  {
      name: "Mew",
      gif : "https://media.tenor.com/u-qWcV0GwbkAAAAC/mew-pokemon.gif",
      type1: "./media/type/ps.png",
      type2: "./media/type/nt.png",
      ev1: x,
      ev2: nt,
      ev3: nt,
  },
]

// of the idpokemon depends on what will be displayed on the screen
let idPokemon = 0;

// this validation is to prevent the gif screen from being empty if the pokemon does not exist
if (idPokemon < 1 || idPokemon > 151) {
  gif.innerHTML = `<img src="${buscandopokemon}">`;
}
if (idPokemon === undefined) idPokemon = 0;

// when pressing the button, the value of the input is taken and passed to the variable id pokemon, and then call the function searchpokemon and pass idpokemon as a parameter
searchButton.addEventListener("click", () => {
    idPokemon = searchInput.value;
    if (idPokemon > 0 && idPokemon < 152) searchPokemon(idPokemon);
  searchInput.value = "";
});

// here a number between 1 and 151 is generated and passed as value to the variable id pokemon, and then call the function searchpokemon and pass it the parameter idpokemon
button.addEventListener("click", () => {
  idPokemon = Math.round(Math.random() * (151 - 1) + 1);
  searchPokemon(idPokemon);
});

function searchPokemon(idPokemon) {

  let pokemon = pokemonList[idPokemon];

  name.innerHTML = `<h3 class="title-container">¡ Guau has encontrado un <span class="pokemon-text-color">${pokemon.name}</span> !</h3>`;
  gif.innerHTML = `<img src='${pokemon.gif}'>`;
  info.innerHTML = `<div>N° en la pokédex: ${idPokemon}</div> <div class="pokemon-type">Tipo:<img src="${pokemon.type1}"><img src="${pokemon.type2}"></div>`;
  evolution.innerHTML = `<span>Evoluciones:</span> <div><img src="${pokemon.ev1}"></div><div><img src="${pokemon.ev2}"></div><div><img src="${pokemon.ev3}"></div>`;
  if (pokemon.name == "Pikachu") return pikachuSong();
  if (pokemon.name == "Meowth") return meowthSong();
  if (pokemon.name == "Chansey") return chanseySong();
  sound.innerHTML = "";
}



function pikachuSong() {
  sound.innerHTML = `<audio autoplay class="display-none">
<source src="./media/audio/pikachu2.mp3" autoplay type="audio/mpeg"/>
</audio>`;
}
function meowthSong() {
  sound.innerHTML = `<audio autoplay class="display-none ">
<source src="./media/audio/meowth_song.mp3" autoplay type="audio/mpeg"/>
</audio>`;
}
function chanseySong() {
  sound.innerHTML = `<audio autoplay class="display-none ">
  <source src="./media/audio/chansey.mp3" autoplay type="audio/mpeg"/>
  </audio>`;
}
