const button = document.getElementById("button");
const name = document.querySelector(".pokemon-text-container");
const gif = document.querySelector(".pokemon-gif-container");
const info = document.querySelector(".pokemon-info");
const evolution = document.querySelector(".pokemon-evolution");
const sound = document.getElementById("sound-container");
const searchButton = document.querySelector(".input-search-button");
const searchInput = document.querySelector(".input-search");

//in the class we define the characteristics that the pokemon will have('ev' = 'evolution')
class Pokemon {
  constructor(id, name, type1, type2,gif, ev1, ev2, ev3) {
    this.id = id;
    this.name = name;
    this.gif = gif;
    this.type1 = `./media/type/${type1}.png`;
    this.type2 = `./media/type/${type2}.png`;
    this.ev1 = ev1;
    this.ev2 = ev2;
    this.ev3 = ev3;
  }
}
const nt = "./media/nt.gif";
const x = "./media/x.gif";
const buscandopokemon = "https://i.makeagif.com/media/8-21-2016/V1OnWi.gif";

const a1 = "https://media.tenor.com/JYtlflYYs9wAAAAM/bulbasaur-nodding.gif";
const a2 = "https://gifs.eco.br/wp-content/uploads/2022/04/gifs-do-ivysaur-0.gif";
const a3 = "https://gifs.eco.br/wp-content/uploads/2022/04/gifs-do-venusaur-1.gif";
const a4 = "https://media.tenor.com/qIhgj8cLz9UAAAAM/charmander-charmander-pokemon.gif";
const a5 = "http://24.media.tumblr.com/189f7d304c9fab589f89e5cd65a109ea/tumblr_mr8jriFfDA1qhd8sao1_500.gif";
const a6 = "http://31.media.tumblr.com/d8865f0b5c3471c70f29afbc71176236/tumblr_ml4msevS3m1r3ifxzo1_500.gif";
const a7 = "https://media.tenor.com/Ken3eHIfWnAAAAAM/pokemon-squirtle.gif";
const a8 = "https://i.pinimg.com/originals/21/36/4d/21364d959852b93ffec98ea9c6bc77b5.gif";
const a9 = "https://media.tenor.com/rLFfSIKDXGoAAAAM/yo-you-good-lmao-yeah-thanks.gif";
const a10 = "https://media.tenor.com/rBRu9Y6AJMMAAAAC/caterpie-caterpillar.gif";
const a11 = "https://sm.mashable.com/mashable_sea/photo/default/9c977814f026a9cbaa86df7cb0c33af6f0df8060-00_67jf.gif";
const a12 = "https://media.tenor.com/A8kgsqhltPIAAAAC/pokemon-pokemon-butterfree.gif";
const a13 = "https://media.tenor.com/rs3U38Pu2XsAAAAM/weedle-pokemon.gif";
const a14 = "https://media.tenor.com/261fjYU3-uoAAAAC/kakuna-pokemon.gif";
const a15 = "https://thumbs.gfycat.com/BlueInstructiveDiplodocus-size_restricted.gif";
const a16 = "https://media.tenor.com/9y3ql3fTKMMAAAAC/pidgey-cute.gif";
const a17 = "https://media.tenor.com/bHL9O-KFgoQAAAAC/pidgeotto-pokemon.gif";
const a18 = "https://media.tenor.com/TS12692KzXcAAAAC/pidgeot-pigeon.gif";
const a19 = "https://media.tenor.com/JI2kGjoQ3_MAAAAC/pokemon-rattata.gif";
const a20 = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTLcSLWKDTzgUrYNI2HGlgLpF2XlDdAEkDBml39Sd3ErbJchVhakf4UaGZSDJQkvHm2ZU&usqp=CAU";
const a21 = "http://24.media.tumblr.com/9701e3cf6a58fce229a5136353279cb7/tumblr_mn61rvvdqV1rjp53to1_400.gif";
const a22 = "https://i.gifer.com/origin/aa/aa569228c585a59f0acd355ee4a3fb3d.gif";
const a23 = "https://media.tenor.com/Oz7Uz-ZMiToAAAAC/ekans-pokemon.gif";
const a24 = "https://media.tenor.com/-oBJrci79jMAAAAC/pokemon-arbok.gif";
const a25 = "https://i.pinimg.com/originals/8a/81/ec/8a81ecd8fdd266b3221da325875c0ea8.gif";
const a26 = "https://media.tenor.com/Nu0eEzo0nOMAAAAC/raichu-raichu-pokemon.gif";
const a27 = "https://i.pinimg.com/originals/ad/7e/82/ad7e82073c11a10bb65b8c11039af0e0.gif";
const a28 = "https://media.tenor.com/6w0Lwo9COFIAAAAC/sandslash-spin.gif";
const a29 = "https://i.pinimg.com/originals/f3/c7/16/f3c716e4a26f3c7204fdc5e00666431a.gif";
const a30 = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCEUCWG2XWgl7NnaJTwjwd-81s5LQov8dSrQTHHJDKQUw97k5U6mYtLQl0O63fdep1dgM&usqp=CAU";
const a31 = "http://pa1.narvii.com/6788/0ea4ebceae39a557afa7c42b286ce0e8d6a2fff5_00.gif";
const a32 = "https://i.gifer.com/origin/f5/f509c95932182166df9a04f25d0c4e11.gif";
const a33 = "http://pa1.narvii.com/6273/fd71cf4398f8420a4260d080e46b76f2bb0ab7d6_00.gif";
const a34 = "https://media.tenor.com/NyxZuUTU6EMAAAAC/nidoking-pok%C3%A9mon-nidoking.gif";
const a35 = "https://thumbs.gfycat.com/CostlyDifficultArabianwildcat-max-1mb.gif";
const a36 = "https://media4.giphy.com/media/TJ2eWMiqkOqQg/giphy.gif";
const a37 = "https://i.gifer.com/origin/39/3930893994563dc851d3c4d35d8a1457.gif";
const a38 = "https://media.tenor.com/DKpixx_akhAAAAAC/ninetales-pokemon.gif";
const a39 = "https://media1.giphy.com/media/eXUlPn1gmZavu/giphy.gif";
const a40 = "https://i.pinimg.com/originals/b4/9f/a1/b49fa10bee8e79905f0487a87110b910.gif";
const a41 = "https://i.gifer.com/8Xk8.gif";
const a42 = "https://media.tenor.com/iGbkGP-vYu8AAAAC/golbat-shadow-ball.gif";
const a43 = "https://media.tenor.com/HFTgIsLNWGUAAAAC/oddish-pokemon.gif";
const a44 = "https://media.tenor.com/NZykCWd-4wEAAAAd/gloom-pokemon.gif";
const a45 = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfnVPW7ZP4aYFVo5w9HHiVYLmISga_yHfWcMvAWYSThKMP1DJ70IXlklnOUtmzJgE6_j0&usqp=CAU";
const a46 = "https://pa1.narvii.com/6186/ff24a1b61d5b1b19484c73b9d6cbd44924a1297a_hq.gif";
const a47 = "https://pa1.narvii.com/5822/6ad4b2d43dda6af8e1630536a1bb51bd544bd1f9_hq.gif";
const a48 = "https://media.tenor.com/gPuwrxxBZ0sAAAAd/venonat-pokemon.gif";
const a49 = "https://64.media.tumblr.com/89f41419b1055d871159d5c180bb4cfc/tumblr_ot8kq4H5OR1vpbs3jo1_640.gif";
const a50 = "https://media.tenor.com/wuw4q53RMPQAAAAC/pokemon-diglett.gif";
const a51 = "https://i.pinimg.com/originals/c5/e3/c4/c5e3c49a927761800b0e2e0dc40ce6b0.gif";
const a52 = "https://i.pinimg.com/originals/d0/62/b1/d062b1147fc2bd3ae3c9db382f3932f0.gif";
const a53 = "https://media.tenor.com/98ZLi9DJPBcAAAAC/pokemon-persian.gif";
const a54 = "https://media.tenor.com/5rbtjevzC1cAAAAC/pokemon-psyduck.gif";
const a55 = "https://i.gifer.com/C7h8.gif";
const a56 = "https://64.media.tumblr.com/32dec5fccabad564e61a3bab24c028eb/tumblr_o3hg2g7vfI1rnrreio1_640.gifv";
const a57 = "https://64.media.tumblr.com/ac77943c9db74082a66937e7c3a4ae11/tumblr_og6ykea52k1tgjlm2o1_500.gif";
const a58 = "https://thumbs.gfycat.com/AcidicAshamedBooby-size_restricted.gif";
const a59 = "https://i.pinimg.com/originals/be/90/c2/be90c2f5187281a0f7179c40c0211619.gif";
const a60 = "https://media.tenor.com/DSTbBQBybw8AAAAC/pokemon-poliwag.gif";
const a61 = "https://media.tenor.com/U3-bM1OitDEAAAAC/pokemon-poliwhirl.gif";
const a62 = "https://media.tenor.com/RXOcsOqZt-YAAAAC/poliwhirl-pokemon.gif";
const a63 = "https://media.tenor.com/FQaqgLa0EJ0AAAAC/pokemon-run.gif";
const a64 = "https://24.media.tumblr.com/8cb2f110099499bb8c2b6ae459781eec/tumblr_mi3awaRJAo1r922jeo1_500.gif";
const a65 = "https://media.tenor.com/vuJ4ABnFW8oAAAAC/pokemon-spoon.gif";
const a66 = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d7ebf501-d835-4c15-9782-1332ea9fb086/de2sifi-5c4a637b-b428-42ce-afd7-b225fe0da831.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2Q3ZWJmNTAxLWQ4MzUtNGMxNS05NzgyLTEzMzJlYTlmYjA4NlwvZGUyc2lmaS01YzRhNjM3Yi1iNDI4LTQyY2UtYWZkNy1iMjI1ZmUwZGE4MzEuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.m0B5QI6Tc1v8i_vYqNf9dpkFB86oFYGjkOf46l42q8c";
const a67 = "https://thumbs.gfycat.com/BitterSmugAngelfish-size_restricted.gif";
const a68 = "https://64.media.tumblr.com/2f4afc7f236e8ad21c27b72a44e961cc/tumblr_nsn80eKs4N1tgjlm2o1_500.gif";
const a69 = "https://i.pinimg.com/originals/8f/2f/d4/8f2fd4e6df839a342b8612c7c8b851d7.gif";
const a70 = "https://64.media.tumblr.com/e7d646549b9ea800b85238cc87eb7bdb/25bee2a60db72dc2-f9/s640x960/922c774fd6cd33058031411a9eaab929f6e7d792.gif";
const a71 = "https://64.media.tumblr.com/bb96b3c20a3855612774c9fffda4ad16/tumblr_nd058dLkAM1tqptlzo1_500.gif";
const a72 = "https://64.media.tumblr.com/4346aa7491504bebc7818db4d36462f1/tumblr_mgwjappDd31qd87hlo1_500.gif";
const a73 = "https://media.tenor.com/X-m58xs73uUAAAAC/tentacruel-pokemon.gif";
const a74 = "https://media0.giphy.com/media/bBbqh3SLbKAcE/giphy.gif";
const a75 = "https://64.media.tumblr.com/b87e15321e5c87d7af483c28afc7808b/tumblr_nakkw5BfF01ttdkobo3_400.gif";
const a76 = "https://i.gifer.com/9FeC.gif";
const a77 = "https://i.gifer.com/origin/7d/7d1ea43b523687bf5603ff60af49c69f.gif";
const a78 = "https://media.tenor.com/9PBJqh_8CWkAAAAC/rapidash-pokemon.gif";
const a79 = "https://media.tenor.com/MTnIZZmt72sAAAAC/slowpoke-pokemon.gif";
const a80 = "http://pa1.narvii.com/6316/898401ca0063e6a30835ba3d476b5f15eba1a32a_00.gif";
const a81 = "https://pa1.narvii.com/6377/0b1cc3354fcc2fddb875bd05940223b866d61e05_hq.gif";
const a82 = "https://64.media.tumblr.com/15e328ddbc3a3cf015c1d7b4bd8fdd65/tumblr_mnohunQzG61qhd8sao1_500.gifv";
const a83 = "https://i.pinimg.com/originals/aa/dc/bb/aadcbbc32d86849f9dde362bb0d1f7f8.gif";
const a84 = "http://pa1.narvii.com/5785/ea3d858e3d339198b79ffaf14d3782bb0fee29c4_hq.gif";
const a85 = "https://pa1.narvii.com/5873/91b6e41486989f6cd9789bf93d13ba59371d64f7_hq.gif";
const a86 = "https://pa1.narvii.com/5987/4ae53939ce2b15d9d1380da297c6e939ae29a01c_hq.gif";
const a87 = "https://31.media.tumblr.com/318118a6a3bca66fafa1987dc7279e23/tumblr_mjtufaSfx01rp6axuo1_r1_500.gif";
const a88 = "https://64.media.tumblr.com/tumblr_m5427i0I9C1qkaxaxo1_500.gif";
const a89 = "https://media.tenor.com/yA8BrZ9KshUAAAAC/muk-pokemon.gif";
const a90 = "https://media.tenor.com/LinPC1c8hoAAAAAC/shellder-haze.gif";
const a91 = "https://64.media.tumblr.com/b089347875b869c881b927be5c7117fb/tumblr_okze5rp8YQ1s5fnj9o1_540.gif";
const a92 = "https://i.gifer.com/origin/f6/f6ee07b3d00b82f734b630454add16de.gif";
const a93 = "http://25.media.tumblr.com/7190fe583783c542256eb76522eb4794/tumblr_moion3v15L1qhd8sao1_500.gif";
const a94 = "https://media.tenor.com/sBX3uFWy4woAAAAC/gengar-daze.gif";
const a95 = "https://media.tenor.com/bUOPWft1ZdEAAAAC/pok%C3%A9mon-onix.gif";
const a96 = "https://thumbs.gfycat.com/CheerfulDimAnhinga-size_restricted.gif";
const a97 = "https://media.tenor.com/SeNPABrnbpkAAAAC/pokemon-hypno.gif";
const a98 = "https://media.tenor.com/kp_x95g0th0AAAAC/krabby-pokemon-bubbles-kraby-kingler.gif";
const a99 = "https://media.tenor.com/32t_NW33P34AAAAC/kingler-pokemon.gif";
const a100 = "https://thumbs.gfycat.com/DependableFaintFritillarybutterfly-max-1mb.gif";
const a101 = "https://i.gifer.com/8XnJ.gif";
const a102 = "https://pa1.narvii.com/6163/38b9242cfb26a1fa10e44799082756b792c2d686_hq.gif";
const a103 = "https://i.gifer.com/origin/1f/1fb3c7b70e5359dcfd00d51f6c33527a.gif";
const a104 = "http://24.media.tumblr.com/tumblr_mbott3v9gu1rzsfkvo1_500.gif";
const a105 = "https://i.gifer.com/origin/ee/ee06c03c390c32587f07158f3b0fc045.gif";
const a106 = "https://media.tenor.com/En_rjgT9YZgAAAAC/pok%C3%A9mon-hitmonlee.gif";
const a107 = "https://i.pinimg.com/originals/e8/db/0c/e8db0c42877f9c855303e5e1bbd8f056.gif";
const a108 = "https://i.gifer.com/origin/a0/a0a3d6f90415bb4892fc2fa03fd88745.gif";
const a109 = "https://media.tenor.com/UUvLY3WqDkIAAAAC/koffing-pokemon.gif";
const a110 = "https://media.tenor.com/08AMleg9izgAAAAC/weezing-pokemon.gif";
const a111 = "https://i.gifer.com/origin/7f/7f98f3a41381394dd8a41fe7c3139fee_w200.gif";
const a112 = "https://media.tenor.com/Fm15zYENMFMAAAAC/rhydon-pok%C3%A9mon-rhydon.gif";
const a113 = "https://media.tenor.com/LVesZ_GILwMAAAAC/pokemon-pokemongo.gif";
const a114 = "https://i.pinimg.com/originals/82/c0/b6/82c0b6424f828543b8f2e08aac7ff628.gif";
const a115 = "https://media.tenor.com/4L9ZdeYPPogAAAAC/kangaskhan-pokemon.gif";
const a116 = "http://pa1.narvii.com/6364/aea54484cf218d36d628d81694b55f466453779c_00.gif";
const a117 = "http://24.media.tumblr.com/tumblr_mak2am6uBQ1r3ifxzo1_500.gif";
const a118 = "http://pa1.narvii.com/5705/378ba1b051a66cd4778072a59a741566ec777444_00.gif";
const a119 = "https://24.media.tumblr.com/7f356fca7e02d909315e7b8325afd581/tumblr_mkebpdqTYV1s5mujoo1_500.gif";
const a120 = "https://i.gifer.com/C7h7.gif";
const a121 = "https://i.gifer.com/origin/85/8576b98ad0341fe0e3b1ab762086f24e.gif";
const a122 = "http://pa1.narvii.com/6216/8bfa6520fd57b619dc691d8e460fb2ce0868502f_00.gif";
const a123 = "https://i.gifer.com/C8Ad.gif";
const a124 = "https://media.tenor.com/LlXuCHbLdfwAAAAC/pokemon-ugly.gif";
const a125 = "https://thumbs.gfycat.com/SmoggyTerrificBighornedsheep-size_restricted.gif";
const a126 = "https://media.tenor.com/7UzJzVrZjqoAAAAC/magmar-pok%C3%A9mon-magmar.gif";
const a127 = "https://media.tenor.com/TmSX6n0SYMoAAAAC/pinsir-pok%C3%A9mon-pinsir.gif";
const a128 = "https://media.tenor.com/fleK_6qPJeEAAAAC/tauros-pok%C3%A9mon-tauros.gif";
const a129 = "https://media.tenor.com/LoYLZWgZo5cAAAAC/pokemon-magikarp.gif";
const a130 = "https://media.tenor.com/d5_PknD57wQAAAAC/pokemon-gyarados.gif";
const a131 = "https://media0.giphy.com/media/3vEJiMNgR6cik/giphy.gif";
const a132 = "https://media.tenor.com/IA266nP_INIAAAAC/ditto-pokemon.gif";
const a133 = "https://media4.giphy.com/media/tDJfaLVF0gHV90lxZj/giphy.gif";
const a134 = "https://media.tenor.com/tT4NN73KFmoAAAAC/vaporeon-pokemon.gif";
const a135 = "https://media.tenor.com/Ot8tPXmP9NkAAAAC/jolteon-pok%C3%A9mon-jolteon.gif";
const a136 = "https://media.tenor.com/I3roL4dZDdIAAAAC/flareon-pokemon.gif";
const a137 = "https://media.tenor.com/iCfvJtBBxoIAAAAC/porygon-pokemon.gif";
const a138 = "https://media.tenor.com/P1tr8EUQt_MAAAAM/helix.gif";
const a139 = "https://i.kym-cdn.com/photos/images/original/000/935/343/dbe.gif";
const a140 = "https://media.tenor.com/-FJvxV0F28kAAAAC/pokemon-kabuto.gif";
const a141 = "https://media.tenor.com/0if-W6m11rAAAAAC/kabutops-pok%C3%A9mon-kabutops.gif";
const a142 = "https://media.tenor.com/KrnQrppD8cUAAAAC/aerodactyl-pok%C3%A9mon.gif";
const a143 = "https://media.tenor.com/dNDyTR73jOkAAAAM/snorlax.gif";
const a144 = "https://media.tenor.com/hwhT-mxGKV0AAAAC/pokemon-articuno.gif";
const a145 = "https://media.tenor.com/_Iw-Y8BCKuEAAAAC/zapdos-pokemon.gif";
const a146 = "https://media.tenor.com/VuI7lLFmimQAAAAC/moltres-pokemon.gif";
const a147 = "https://media.tenor.com/75pZWZSt490AAAAC/dratini-pokemon.gif";
const a148 = "https://i.gifer.com/BnIy.gif";
const a149 = "https://media.tenor.com/vTNxZtc3EoMAAAAC/dragonite-pokemon.gif";
const a150 = "https://media1.giphy.com/media/7ProItiELBagM/giphy.gif";
const a151 = "https://media.tenor.com/u-qWcV0GwbkAAAAC/mew-pokemon.gif";

const b1 = "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif";
const b2 = "https://projectpokemon.org/images/normal-sprite/ivysaur.gif";
const b3 = "https://projectpokemon.org/images/normal-sprite/venusaur.gif";
const b4 = "https://projectpokemon.org/images/normal-sprite/charmander.gif";
const b5 = "https://projectpokemon.org/images/normal-sprite/charmeleon.gif";
const b6 = "https://projectpokemon.org/images/normal-sprite/charizard.gif";
const b7 = "https://projectpokemon.org/images/normal-sprite/squirtle.gif";
const b8 = "https://projectpokemon.org/images/normal-sprite/wartortle.gif";
const b9 = "https://projectpokemon.org/images/normal-sprite/blastoise.gif";
const b10 = "https://projectpokemon.org/images/normal-sprite/caterpie.gif";
const b11 = "https://projectpokemon.org/images/normal-sprite/metapod.gif";
const b12 = "https://projectpokemon.org/images/normal-sprite/butterfree.gif";
const b13 = "https://projectpokemon.org/images/normal-sprite/weedle.gif";
const b14 = "https://projectpokemon.org/images/normal-sprite/kakuna.gif";
const b15 = "https://projectpokemon.org/images/normal-sprite/beedrill.gif";
const b16 = "https://projectpokemon.org/images/normal-sprite/pidgey.gif";
const b17 = "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif";
const b18 = "https://projectpokemon.org/images/normal-sprite/pidgeot.gif";
const b19 = "https://projectpokemon.org/images/normal-sprite/rattata.gif";
const b20 = "https://projectpokemon.org/images/normal-sprite/raticate.gif";
const b21 = "https://projectpokemon.org/images/normal-sprite/spearow.gif";
const b22 = "https://projectpokemon.org/images/normal-sprite/fearow.gif";
const b23 = "https://projectpokemon.org/images/normal-sprite/ekans.gif";
const b24 = "https://projectpokemon.org/images/normal-sprite/arbok.gif";
const b25 = "https://projectpokemon.org/images/normal-sprite/pikachu.gif";
const b26 = "https://projectpokemon.org/images/normal-sprite/raichu.gif";
const b27 = "https://projectpokemon.org/images/normal-sprite/sandshrew.gif";
const b28 = "https://projectpokemon.org/images/normal-sprite/sandslash.gif";
const b29 = "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif";
const b30 = "https://projectpokemon.org/images/normal-sprite/nidorina.gif";
const b31 = "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif";
const b32 = "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif";
const b33 = "https://projectpokemon.org/images/normal-sprite/nidorino.gif";
const b34 = "https://projectpokemon.org/images/normal-sprite/nidoking.gif";
const b35 = "https://projectpokemon.org/images/normal-sprite/clefairy.gif";
const b36 = "https://projectpokemon.org/images/normal-sprite/clefable.gif";
const b37 = "https://projectpokemon.org/images/normal-sprite/vulpix.gif";
const b38 = "https://projectpokemon.org/images/normal-sprite/ninetales.gif";
const b39 = "https://projectpokemon.org/images/normal-sprite/jigglypuff.gif";
const b40 = "https://projectpokemon.org/images/normal-sprite/wigglytuff.gif";
const b41 = "https://projectpokemon.org/images/normal-sprite/zubat.gif";
const b42 = "https://projectpokemon.org/images/normal-sprite/golbat.gif";
const b43 = "https://projectpokemon.org/images/normal-sprite/oddish.gif";
const b44 = "https://projectpokemon.org/images/normal-sprite/gloom.gif";
const b45 = "https://projectpokemon.org/images/normal-sprite/vileplume.gif";
const b46 = "https://projectpokemon.org/images/normal-sprite/paras.gif";
const b47 = "https://projectpokemon.org/images/normal-sprite/parasect.gif";
const b48 = "https://projectpokemon.org/images/normal-sprite/venonat.gif";
const b49 = "https://projectpokemon.org/images/normal-sprite/venomoth.gif";
const b50 = "https://projectpokemon.org/images/normal-sprite/diglett.gif";
const b51 = "https://projectpokemon.org/images/normal-sprite/dugtrio.gif";
const b52 = "https://projectpokemon.org/images/normal-sprite/meowth.gif";
const b53 = "https://projectpokemon.org/images/normal-sprite/persian.gif";
const b54 = "https://projectpokemon.org/images/normal-sprite/psyduck.gif";
const b55 = "https://projectpokemon.org/images/normal-sprite/golduck.gif";
const b56 = "https://projectpokemon.org/images/normal-sprite/mankey.gif";
const b57 = "https://projectpokemon.org/images/normal-sprite/primeape.gif";
const b58 = "https://projectpokemon.org/images/normal-sprite/growlithe.gif";
const b59 = "https://projectpokemon.org/images/normal-sprite/arcanine.gif";
const b60 = "https://projectpokemon.org/images/normal-sprite/poliwag.gif";
const b61 = "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif";
const b62 = "https://projectpokemon.org/images/normal-sprite/poliwrath.gif";
const b63 = "https://projectpokemon.org/images/normal-sprite/abra.gif";
const b64 = "https://projectpokemon.org/images/normal-sprite/kadabra.gif";
const b65 = "https://projectpokemon.org/images/normal-sprite/alakazam.gif";
const b66 = "https://projectpokemon.org/images/normal-sprite/machop.gif";
const b67 = "https://projectpokemon.org/images/normal-sprite/machoke.gif";
const b68 = "https://projectpokemon.org/images/normal-sprite/machamp.gif";
const b69 = "https://projectpokemon.org/images/normal-sprite/bellsprout.gif";
const b70 = "https://projectpokemon.org/images/normal-sprite/weepinbell.gif";
const b71 = "https://projectpokemon.org/images/normal-sprite/victreebel.gif";
const b72 = "https://projectpokemon.org/images/normal-sprite/tentacool.gif";
const b73 = "https://projectpokemon.org/images/normal-sprite/tentacruel.gif";
const b74 = "https://projectpokemon.org/images/normal-sprite/geodude.gif";
const b75 = "https://projectpokemon.org/images/normal-sprite/graveler.gif";
const b76 = "https://projectpokemon.org/images/normal-sprite/golem.gif";
const b77 = "https://projectpokemon.org/images/normal-sprite/ponyta.gif";
const b78 = "https://projectpokemon.org/images/normal-sprite/rapidash.gif";
const b79 = "https://projectpokemon.org/images/normal-sprite/slowpoke.gif";
const b80 = "https://projectpokemon.org/images/normal-sprite/slowbro.gif";
const b81 = "https://projectpokemon.org/images/normal-sprite/magnemite.gif";
const b82 = "https://projectpokemon.org/images/normal-sprite/magneton.gif";
const b84 = "https://projectpokemon.org/images/normal-sprite/doduo.gif";
const b85 = "https://projectpokemon.org/images/normal-sprite/dodrio.gif";
const b86 = "https://projectpokemon.org/images/normal-sprite/seel.gif";
const b87 = "https://projectpokemon.org/images/normal-sprite/dewgong.gif";
const b88 = "https://projectpokemon.org/images/normal-sprite/grimer.gif";
const b89 = "https://projectpokemon.org/images/normal-sprite/muk.gif";
const b90 = "https://projectpokemon.org/images/normal-sprite/shellder.gif";
const b91 = "https://projectpokemon.org/images/normal-sprite/cloyster.gif";
const b92 = "https://projectpokemon.org/images/normal-sprite/gastly.gif";
const b93 = "https://projectpokemon.org/images/normal-sprite/haunter.gif";
const b94 = "https://projectpokemon.org/images/normal-sprite/gengar.gif";
const b96 = "https://projectpokemon.org/images/normal-sprite/drowzee.gif";
const b97 = "https://projectpokemon.org/images/normal-sprite/hypno.gif";
const b98 = "https://projectpokemon.org/images/normal-sprite/krabby.gif";
const b99 = "https://projectpokemon.org/images/normal-sprite/kingler.gif";
const b100 = "https://projectpokemon.org/images/normal-sprite/voltorb.gif";
const b101 = "https://projectpokemon.org/images/normal-sprite/electrode.gif";
const b102 = "https://projectpokemon.org/images/normal-sprite/exeggcute.gif";
const b103 = "https://projectpokemon.org/images/normal-sprite/exeggutor.gif";
const b104 = "https://projectpokemon.org/images/normal-sprite/cubone.gif";
const b105 = "https://projectpokemon.org/images/normal-sprite/marowak.gif";
const b109 = "https://projectpokemon.org/images/normal-sprite/koffing.gif";
const b110 = "https://projectpokemon.org/images/normal-sprite/weezing.gif";
const b111 = "https://projectpokemon.org/images/normal-sprite/rhyhorn.gif";
const b112 = "https://projectpokemon.org/images/normal-sprite/rhydon.gif";
const b116 = "https://projectpokemon.org/images/normal-sprite/horsea.gif";
const b117 = "https://projectpokemon.org/images/normal-sprite/seadra.gif";
const b118 = "https://projectpokemon.org/images/normal-sprite/goldeen.gif";
const b119 = "https://projectpokemon.org/images/normal-sprite/seaking.gif";
const b120 = "https://projectpokemon.org/images/normal-sprite/staryu.gif";
const b121 = "https://projectpokemon.org/images/normal-sprite/starmie.gif";
const b129 = "https://projectpokemon.org/images/normal-sprite/magikarp.gif";
const b130 = "https://projectpokemon.org/images/normal-sprite/gyarados.gif";
const b133 = "https://projectpokemon.org/images/normal-sprite/eevee.gif";
const b134 = "https://projectpokemon.org/images/normal-sprite/vaporeon.gif";
const b135 = "https://projectpokemon.org/images/normal-sprite/jolteon.gif";
const b136 = "https://projectpokemon.org/images/normal-sprite/flareon.gif";
const b138 = "https://projectpokemon.org/images/normal-sprite/omanyte.gif";
const b139 = "https://projectpokemon.org/images/normal-sprite/omastar.gif";
const b140 = "https://projectpokemon.org/images/normal-sprite/kabuto.gif";
const b141 = "https://projectpokemon.org/images/normal-sprite/kabutops.gif";
const b147 = "https://projectpokemon.org/images/normal-sprite/dratini.gif";
const b148 = "https://projectpokemon.org/images/normal-sprite/dragonair.gif";
const b149 = "https://projectpokemon.org/images/normal-sprite/dragonite.gif";

const Bulbasaur = new Pokemon(1,"Bulbasaur","p","v",a1,b1,b2,b3);
const Ivysaur = new Pokemon(2,"Ivysaur","p","v",a2,b1,b2,b3);
const Venusaur = new Pokemon(3,"Venusaur","p","v",a3,b1,b2,b3);
const Charmander = new Pokemon(4,"Charmander","f","nt",a4,b4,b5,b6);
const Charmeleon = new Pokemon(5,"Charmeleon","f","nt",a5,b4,b5,b6);
const Charizard = new Pokemon(6,"Charizard","f","vv",a6,b4,b5,b6);
const Squirtle = new Pokemon(7,"Squirtle","a","nt",a7,b7,b8,b9);
const Wartortle = new Pokemon(8,"Wartortle","a","nt",a8,b7,b8,b9);
const Blastoise = new Pokemon(9,"Blastoise","a","nt",a9,b7,b8,b9);
const Caterpie = new Pokemon(10,"Caterpie","b","nt",a10,b10,b11,b12);
const Metapod = new Pokemon(11,"Metapod","b","nt",a11,b10,b11,b12);
const Butterfree = new Pokemon(12,"Butterfree","b","nt",a12,b10,b11,b12);
const Weedle = new Pokemon(13,"Weedle","b","v",a13,b13,b14,b15);
const Kakuna = new Pokemon(14,"Kakuna","b","v",a14,b13,b14,b15);
const Beedrill = new Pokemon(15,"Beedrill","b","v",a15,b13,b14,b15);
const Pidgey = new Pokemon(16,"Pidgey","n","vv",a16,b16,b17,b18);
const Pidgeotto = new Pokemon(17,"Pidgeotto","n","vv",a17,b16,b17,b18);
const Pidgeot = new Pokemon(18,"Pidgeot","n","vv",a18,b16,b17,b18);
const Rattata = new Pokemon(19,"Rattata","n","nt",a19,b19,b20,nt);
const Raticate = new Pokemon(20,"Raticate","n","nt",a20,b19,b20,nt);
const Spearow = new Pokemon(21,"Spearow","n","vv",a21,b21,b22,nt);
const Fearow = new Pokemon(22,"Fearow","n","vv",a22,b21,b22,nt);
const Ekans = new Pokemon(23,"Ekans","v","nt",a23,b23,b24,nt);
const Arbok = new Pokemon(24,"Arbok","v","nt",a24,b23,b24,nt);
const Pikachu = new Pokemon(25,"Pikachu","e","nt",a25,b25,b26,nt);
const Raichu = new Pokemon(26,"Raichu","e","nt",a26,b25,b26,nt);
const Sandshrew = new Pokemon(27,"Sandshrew","t","nt",a27,b27,b28,nt);
const Sandslash = new Pokemon(28,"Sandslash","t","nt",a128,b27,b28,nt);
const NidoranH = new Pokemon(29,"Nidoran♀","v","nt",a29,b29,b30,b31);
const Nidorina = new Pokemon(30,"Nidorina","v","nt",a30,b29,b30,b31);
const Nidoqueen = new Pokemon(31,"Nidoqueen","v","t",a31,b29,b30,b31);
const NidoranM = new Pokemon(32,"Nidoran♂","v","nt",a32,b32,b33,b34);
const Nidorino = new Pokemon(33,"Nidorino","v","nt",a33,b32,b33,b34);
const Nidoking = new Pokemon(34,"Nidoking","v","t",a34,b32,b33,b34);
const Clefairy = new Pokemon(35,"Clefairy","h","nt",a35,b35,b36,nt);
const Clefable = new Pokemon(36,"Clefable","h","nt",a36,b35,b36,nt);
const Vulpix = new Pokemon(37,"Vulpix","f","nt",a37,b37,b38,nt);
const Ninetales = new Pokemon(38,"Ninetales","f","nt",a38,b37,b38,nt);
const Jigglypuff = new Pokemon(39,"Jigglypuff","n","h",a39,b39,b40,nt);
const Wigglytuff = new Pokemon(40,"Wigglytuff","n","h",a40,b39,b40,nt);
const Zubat = new Pokemon(41,"Zubat","n","vv",a41,b41,b42,nt);
const Golbat = new Pokemon(42,"Golbat","n","vv",a42,b41,b42,nt);
const Oddish = new Pokemon(43,"Oddish","p","v",a43,b43,b44,b45);
const Gloom = new Pokemon(44,"Gloom","p","v",a44,b43,b44,b45);
const Vileplume = new Pokemon(45,"Vileplume","p","v",a45,b43,b44,b45);
const Paras = new Pokemon(46,"Paras","b","p",a46,b46,b47,nt);
const Parasect = new Pokemon(47,"Parasect","b","p",a47,b46,b47,nt);
const Venonat = new Pokemon(48,"Venonat","b","v",a48,b48,b49,nt);
const Venomoth = new Pokemon(49,"Venomoth","b","v",a49,b48,b49,nt);
const Diglett = new Pokemon(50,"Diglett","t","nt",a50,b50,b51,nt);
const Dugtrio = new Pokemon(51,"Dugtrio","t","nt",a51,b50,b51,nt);
const Meowth = new Pokemon(52,"Meowth","n","nt",a52,b52,b53,nt);
const Persian = new Pokemon(53,"Persian","n","nt",a53,b52,b53,nt);
const Psyduck = new Pokemon(54,"Psyduck","a","nt",a54,b54,b55,nt);
const Golduck = new Pokemon(55,"Golduck","a","nt",a55,b54,b55,nt);
const Mankey = new Pokemon(56,"Mankey","l","nt",a56,b56,b57,nt);
const Primeape = new Pokemon(57,"Primeape","l","nt",a57,b56,b57,nt);
const Growlithe = new Pokemon(58,"Growlithe","f","nt",a58,b58,b59,nt);
const Arcanine = new Pokemon(59,"Arcanine","f","nt",a59,b58,b59,nt);
const Poliwag = new Pokemon(60,"Poliwag","a","nt",a60,b60,b61,b62);
const Poliwhirl = new Pokemon(61,"Poliwhirl","a","nt",a61,b60,b61,b62);
const Poliwrath = new Pokemon(62,"Poliwrath","a","l",a62,b60,b61,b62);
const Abra = new Pokemon(63,"Abra","ps","nt",a63,b63,b64,b65);
const Kadabra = new Pokemon(64,"Kadabra","ps","nt",a64,b63,b64,b65);
const Alakazam = new Pokemon(65,"Alakazam","ps","nt",a65,b63,b64,b65);
const Machop = new Pokemon(66,"Machop","l","nt",a66,b66,b67,b68);
const Machoke = new Pokemon(67,"Machoke","l","nt",a67,b66,b67,b68);
const Machamp = new Pokemon(68,"Machamp","l","nt",a68,b66,b67,b68);
const Bellsprout = new Pokemon(69,"Bellsprout","p","v",a69,b69,b70,b71);
const Weepinbell = new Pokemon(70,"Weepinbell","p","v",a70,b69,b70,b71);
const Victreebel = new Pokemon(71,"Victreebel","p","v",a71,b69,b70,b71);
const Tentacool = new Pokemon(72,"Tentacool","a","v",a72,b72,b73,nt);
const Tentacruel = new Pokemon(73,"Tentacruel","a","v",a73,b72,b73,nt);
const Geodude = new Pokemon(74,"Geodude","r","t",a74,b74,b75,b76);
const Graveler = new Pokemon(75,"Graveler","r","t",a75,b74,b75,b76);
const Golem = new Pokemon(76,"Golem","r","t",a76,b74,b75,b76);
const Ponyta = new Pokemon(77,"Ponyta","f","nt",a77,b77,b78,nt);
const Rapidash = new Pokemon(78,"Rapidash","f","nt",a78,b77,b78,nt);
const Slowpoke = new Pokemon(79,"Slowpoke","a","ps",a79,b79,b80,nt);
const Slowbro = new Pokemon(80,"Slowbro","a","ps",a80,b79,b80,nt);
const Magnemite = new Pokemon(81,"Magnemite","e","ac",a81,b81,b82,nt);
const Magneton = new Pokemon(82,"Magneton","e","ac",a82,b81,b82,nt);
const Farfetchd = new Pokemon(83,"Farfetch'd","n","vv",a83,x,nt,nt);
const Doduo = new Pokemon(84,"Doduo","n","vv",a84,b84,b85,nt);
const Dodrio = new Pokemon(85,"Dodrio","n","vv",a85,b84,b85,nt);
const Seel = new Pokemon(86,"Seel","a","nt",a86,b86,b87,nt);
const Dewgong = new Pokemon(87,"Dewgong","a","hi",a87,b86,b87,nt);
const Grimer = new Pokemon(88,"Grimer","v","nt",a88,b88,b89,nt);
const Muk = new Pokemon(89,"Muk","v","nt",a89,b88,b89,nt);
const Shellder = new Pokemon(90,"Shellder","a","nt",a90,b90,b91,nt);
const Cloyster = new Pokemon(91,"Cloyster","a","hi",a91,b90,b91,nt);
const Gastly = new Pokemon(92,"Gastly","fa","v",a92,b92,b93,b94);
const Haunter = new Pokemon(93,"Haunter","fa","v",a93,b92,b93,b94);
const Gengar = new Pokemon(94,"Gengar","fa","v",a94,b92,b93,b94);
const Onix = new Pokemon(95,"Onix","r","t",a95,x,nt,nt);
const Drowzee = new Pokemon(96,"Drowzee","ps","nt",a96,b96,b97,nt);
const Hypno = new Pokemon(97,"Hypno","ps","nt",a97,b96,b97,nt);
const Krabby = new Pokemon(98,"Krabby","a","nt",a98,b98,b99,nt);
const Kingler = new Pokemon(99,"Kingler","a","nt",a99,b98,b99,nt);
const Voltorb = new Pokemon(100,"Voltorb","e","nt",a100,b100,b101,nt);
const Electrode = new Pokemon(101,"Electrode","e","nt",a101,b100,b101,nt);
const Exeggcute = new Pokemon(102,"Exeggcute","p","ps",a102,b102,b103,nt);
const Exeggutor = new Pokemon(103,"Exeggutor","p","ps",a103,b102,b103,nt);
const Cubone = new Pokemon(104,"Cubone","t","nt",a104,b104,b105,nt);
const Marowak = new Pokemon(105,"Marowak","t","nt",a105,b104,b105,nt);
const Hitmonlee = new Pokemon(106,"Hitmonlee","l","nt",a106,x,nt,nt);
const Hitmonchan = new Pokemon(107,"Hitmonchan","l","nt",a107,x,nt,nt);
const Lickitung = new Pokemon(108,"Lickitung","n","nt",a108,x,nt,nt);
const Koffing = new Pokemon(109,"Koffing","v","nt",a109,b109,b110,nt);
const Weezing = new Pokemon(110,"Weezing","v","nt",a110,b109,b110,nt);
const Rhyhorn = new Pokemon(111,"Rhyhorn","t","r",a111,b111,b112,nt);
const Rhydon = new Pokemon(112,"Rhydon","t","r",a112,b111,b112,nt);
const Chansey = new Pokemon(113,"Chansey","n","nt",a113,x,nt,nt);
const Tangela = new Pokemon(114,"Tangela","p","nt",a114,x,nt,nt);
const Kangaskhan = new Pokemon(115,"Kangaskhan","n","nt",a115,x,nt,nt);
const Horsea = new Pokemon(116,"Horsea","a","nt",a116,b116,b117,nt);
const Seadra = new Pokemon(117,"Seadra","a","nt",a117,b116,b117,nt);
const Goldeen = new Pokemon(118,"Goldeen","a","nt",a118,b118,b119,nt);
const Seaking = new Pokemon(119,"Seaking","a","nt",a119,b118,b119,nt);
const Staryu = new Pokemon(120,"Staryu","a","nt",a120,b120,b121,nt);
const Starmie = new Pokemon(121,"	Starmie","a","ps",a121,b120,b121,nt);
const MrMime = new Pokemon(122,"Mr. Mime","ps","h",a122,x,nt,nt);
const Scyther = new Pokemon(123,"Scyther","b","vv",a123,x,nt,nt);
const Jynx = new Pokemon(124,"Jynx","hi","ps",a124,x,nt,nt);
const Electabuzz = new Pokemon(125,"Electabuzz","e","nt",a125,x,nt,nt);
const Magmar = new Pokemon(126,"Magmar","f","nt",a126,x,nt,nt);
const Pinsir = new Pokemon(127,"Pinsir","b","nt",a127,x,nt,nt);
const Tauros = new Pokemon(128,"Tauros","n","nt",a128,x,nt,nt);
const Magikarp = new Pokemon(129,"Magikarp","a","nt",a129,b129,b130,nt);
const Gyarados = new Pokemon(130,"Gyarados","a","vv",a130,b129,b130,nt);
const Lapras = new Pokemon(131,"Lapras","a","hi",a131,x,nt,nt);
const Ditto = new Pokemon(132,"Ditto","n","nt",a132,x,nt,nt);
const Eevee = new Pokemon(133,"Eevee","n","nt",a133,b134,b135,b136);
const Vaporeon = new Pokemon(134,"Vaporeon","a","nt",a134,b133,b134,nt);
const Jolteon = new Pokemon(135,"Jolteon","e","nt",a135,b133,b135,nt);
const Flareon = new Pokemon(136,"Flareon","f","nt",a136,b133,b136,nt);
const Porygon = new Pokemon(137,"Porygon","n","nt",a137,x,nt,nt);
const Omanyte = new Pokemon(138,"Omanyte","r","a",a138,b138,b139,nt);
const Omastar = new Pokemon(139,"Omastar","r","a",a139,b138,b139,nt);
const Kabuto = new Pokemon(140,"Kabuto","r","a",a140,b140,b141,nt);
const Kabutops = new Pokemon(141,"Kabutops","r","a",a141,b140,b141,nt);
const Aerodactyl = new Pokemon(142,"Aerodactyl","r","vv",a142,x,nt,nt);
const Snorlax = new Pokemon(143,"Snorlax","n","nt",a143,x,nt,nt);
const Articuno = new Pokemon(144,"Articuno","hi","vv",a144,x,nt,nt);
const Zapdos = new Pokemon(145,"Zapdos","e","vv",a145,x,nt,nt);
const Moltres = new Pokemon(146,"Moltres","f","vv",a146,x,nt,nt);
const Dratini = new Pokemon(147,"Dratini","d","nt",a147,b147,b148,b149);
const Dragonair = new Pokemon(148,"Dragonair","d","nt",a148,b147,b148,b149);
const Dragonite = new Pokemon(149,"Dragonite","d","vv",a149,b147,b148,b149);
const Mewtwo = new Pokemon(150,"Mewtwo","ps","nt",a150,x,nt,nt);
const Mew = new Pokemon(151,"Mew","ps","nt",a151,x,nt,nt);

// of the idpokemon depends on what will be displayed on the screen
let idPokemon = 0;

// this validation is to prevent the gif screen from being empty if the pokemon does not exist
if (idPokemon < 1 || idPokemon > 151) {
  gif.innerHTML = `<img src="${buscandopokemon}">`;
}
if (idPokemon === undefined) idPokemon = 0;

// when pressing the button, the value of the input is taken and passed to the variable id pokemon, and then call the function searchpokemon and pass idpokemon as a parameter
searchButton.addEventListener("click", () => {
  idPokemon = searchInput.value;
  if (idPokemon > 0 && idPokemon < 152) searchPokemon(idPokemon);
  searchInput.value = "";
});

// here a number between 1 and 151 is generated and passed as value to the variable id pokemon, and then call the function searchpokemon and pass it the parameter idpokemon
button.addEventListener("click", () => {
  idPokemon = Math.round(Math.random() * (151 - 1) + 1);
  searchPokemon(idPokemon);
});

function searchPokemon(idPokemon) {
  let pokemon = "";
  if (idPokemon == 1) pokemon = Bulbasaur;
  if (idPokemon == 2) pokemon = Ivysaur;
  if (idPokemon == 3) pokemon = Venusaur;
  if (idPokemon == 4) pokemon = Charmander;
  if (idPokemon == 5) pokemon = Charmeleon;
  if (idPokemon == 6) pokemon = Charizard;
  if (idPokemon == 7) pokemon = Squirtle;
  if (idPokemon == 8) pokemon = Wartortle;
  if (idPokemon == 9) pokemon = Blastoise;
  if (idPokemon == 10) pokemon = Caterpie;
  if (idPokemon == 11) pokemon = Metapod;
  if (idPokemon == 12) pokemon = Butterfree;
  if (idPokemon == 13) pokemon = Weedle;
  if (idPokemon == 14) pokemon = Kakuna;
  if (idPokemon == 15) pokemon = Beedrill;
  if (idPokemon == 16) pokemon = Pidgey;
  if (idPokemon == 17) pokemon = Pidgeotto;
  if (idPokemon == 18) pokemon = Pidgeot;
  if (idPokemon == 19) pokemon = Rattata;
  if (idPokemon == 20) pokemon = Raticate;
  if (idPokemon == 21) pokemon = Spearow;
  if (idPokemon == 22) pokemon = Fearow;
  if (idPokemon == 23) pokemon = Ekans;
  if (idPokemon == 24) pokemon = Arbok;
  if (idPokemon == 25) pokemon = Pikachu;
  if (idPokemon == 26) pokemon = Raichu;
  if (idPokemon == 27) pokemon = Sandshrew;
  if (idPokemon == 28) pokemon = Sandslash;
  if (idPokemon == 29) pokemon = NidoranH;
  if (idPokemon == 30) pokemon = Nidorina;
  if (idPokemon == 31) pokemon = Nidoqueen;
  if (idPokemon == 32) pokemon = NidoranM;
  if (idPokemon == 33) pokemon = Nidorino;
  if (idPokemon == 34) pokemon = Nidoking;
  if (idPokemon == 35) pokemon = Clefairy;
  if (idPokemon == 36) pokemon = Clefable;
  if (idPokemon == 37) pokemon = Vulpix;
  if (idPokemon == 38) pokemon = Ninetales;
  if (idPokemon == 39) pokemon = Jigglypuff;
  if (idPokemon == 40) pokemon = Wigglytuff;
  if (idPokemon == 41) pokemon = Zubat;
  if (idPokemon == 42) pokemon = Golbat;
  if (idPokemon == 43) pokemon = Oddish;
  if (idPokemon == 44) pokemon = Gloom;
  if (idPokemon == 45) pokemon = Vileplume;
  if (idPokemon == 46) pokemon = Paras;
  if (idPokemon == 47) pokemon = Parasect;
  if (idPokemon == 48) pokemon = Venonat;
  if (idPokemon == 49) pokemon = Venomoth;
  if (idPokemon == 50) pokemon = Diglett;
  if (idPokemon == 51) pokemon = Dugtrio;
  if (idPokemon == 52) pokemon = Meowth;
  if (idPokemon == 53) pokemon = Persian;
  if (idPokemon == 54) pokemon = Psyduck;
  if (idPokemon == 55) pokemon = Golduck;
  if (idPokemon == 56) pokemon = Mankey;
  if (idPokemon == 57) pokemon = Primeape;
  if (idPokemon == 58) pokemon = Growlithe;
  if (idPokemon == 59) pokemon = Arcanine;
  if (idPokemon == 60) pokemon = Poliwag;
  if (idPokemon == 61) pokemon = Poliwhirl;
  if (idPokemon == 62) pokemon = Poliwrath;
  if (idPokemon == 63) pokemon = Abra;
  if (idPokemon == 64) pokemon = Kadabra;
  if (idPokemon == 65) pokemon = Alakazam;
  if (idPokemon == 66) pokemon = Machop;
  if (idPokemon == 67) pokemon = Machoke;
  if (idPokemon == 68) pokemon = Machamp;
  if (idPokemon == 69) pokemon = Bellsprout;
  if (idPokemon == 70) pokemon = Weepinbell;
  if (idPokemon == 71) pokemon = Victreebel;
  if (idPokemon == 72) pokemon = Tentacool;
  if (idPokemon == 73) pokemon = Tentacruel;
  if (idPokemon == 74) pokemon = Geodude;
  if (idPokemon == 75) pokemon = Graveler;
  if (idPokemon == 76) pokemon = Golem;
  if (idPokemon == 77) pokemon = Ponyta;
  if (idPokemon == 78) pokemon = Rapidash;
  if (idPokemon == 79) pokemon = Slowpoke;
  if (idPokemon == 80) pokemon = Slowbro;
  if (idPokemon == 81) pokemon = Magnemite;
  if (idPokemon == 82) pokemon = Magneton;
  if (idPokemon == 83) pokemon = Farfetchd;
  if (idPokemon == 84) pokemon = Doduo;
  if (idPokemon == 85) pokemon = Dodrio;
  if (idPokemon == 86) pokemon = Seel;
  if (idPokemon == 87) pokemon = Dewgong;
  if (idPokemon == 88) pokemon = Grimer;
  if (idPokemon == 89) pokemon = Muk;
  if (idPokemon == 90) pokemon = Shellder;
  if (idPokemon == 91) pokemon = Cloyster;
  if (idPokemon == 92) pokemon = Gastly;
  if (idPokemon == 93) pokemon = Haunter;
  if (idPokemon == 94) pokemon = Gengar;
  if (idPokemon == 95) pokemon = Onix;
  if (idPokemon == 96) pokemon = Drowzee;
  if (idPokemon == 97) pokemon = Hypno;
  if (idPokemon == 98) pokemon = Krabby;
  if (idPokemon == 99) pokemon = Kingler;
  if (idPokemon == 100) pokemon = Voltorb;
  if (idPokemon == 101) pokemon = Electrode;
  if (idPokemon == 102) pokemon = Exeggcute;
  if (idPokemon == 103) pokemon = Exeggutor;
  if (idPokemon == 104) pokemon = Cubone;
  if (idPokemon == 105) pokemon = Marowak;
  if (idPokemon == 106) pokemon = Hitmonlee;
  if (idPokemon == 107) pokemon = Hitmonchan;
  if (idPokemon == 108) pokemon = Lickitung;
  if (idPokemon == 109) pokemon = Koffing;
  if (idPokemon == 110) pokemon = Weezing;
  if (idPokemon == 111) pokemon = Rhyhorn;
  if (idPokemon == 112) pokemon = Rhydon;
  if (idPokemon == 113) pokemon = Chansey;
  if (idPokemon == 114) pokemon = Tangela;
  if (idPokemon == 115) pokemon = Kangaskhan;
  if (idPokemon == 116) pokemon = Horsea;
  if (idPokemon == 117) pokemon = Seadra;
  if (idPokemon == 118) pokemon = Goldeen;
  if (idPokemon == 119) pokemon = Seaking;
  if (idPokemon == 120) pokemon = Staryu;
  if (idPokemon == 121) pokemon = Starmie;
  if (idPokemon == 122) pokemon = MrMime;
  if (idPokemon == 123) pokemon = Scyther;
  if (idPokemon == 124) pokemon = Jynx;
  if (idPokemon == 125) pokemon = Electabuzz;
  if (idPokemon == 126) pokemon = Magmar;
  if (idPokemon == 127) pokemon = Pinsir;
  if (idPokemon == 128) pokemon = Tauros;
  if (idPokemon == 129) pokemon = Magikarp;
  if (idPokemon == 130) pokemon = Gyarados;
  if (idPokemon == 131) pokemon = Lapras;
  if (idPokemon == 132) pokemon = Ditto;
  if (idPokemon == 133) pokemon = Eevee;
  if (idPokemon == 134) pokemon = Vaporeon;
  if (idPokemon == 135) pokemon = Jolteon;
  if (idPokemon == 136) pokemon = Flareon;
  if (idPokemon == 137) pokemon = Porygon;
  if (idPokemon == 138) pokemon = Omanyte;
  if (idPokemon == 139) pokemon = Omastar;
  if (idPokemon == 140) pokemon = Kabuto;
  if (idPokemon == 141) pokemon = Kabutops;
  if (idPokemon == 142) pokemon = Aerodactyl;
  if (idPokemon == 143) pokemon = Snorlax;
  if (idPokemon == 144) pokemon = Articuno;
  if (idPokemon == 145) pokemon = Zapdos;
  if (idPokemon == 146) pokemon = Moltres;
  if (idPokemon == 147) pokemon = Dratini;
  if (idPokemon == 148) pokemon = Dragonair;
  if (idPokemon == 149) pokemon = Dragonite;
  if (idPokemon == 150) pokemon = Mewtwo;
  if (idPokemon == 151) pokemon = Mew;

  name.innerHTML = `<h3 class="title-container">¡ Guau has encontrado un <span class="pokemon-text-color">${pokemon.name}</span> !</h3>`;
  gif.innerHTML = `<img src='${pokemon.gif}'>`;
  info.innerHTML = `<div>N° en la pokédex: ${pokemon.id}</div> <div class="pokemon-type">Tipo:<img src="${pokemon.type1}"><img src="${pokemon.type2}"></div>`;
  evolution.innerHTML = `<span>Evoluciones:</span> <div><img src="${pokemon.ev1}"></div><div><img src="${pokemon.ev2}"></div><div><img src="${pokemon.ev3}"></div>`;
  if (pokemon == Pikachu) return pikachuSong();
  if (pokemon == Meowth) return meowthSong();
  if (pokemon == Chansey) return chanseySong();
  sound.innerHTML = "";
}



function pikachuSong() {
  sound.innerHTML = `<audio autoplay class="display-none">
<source src="./media/audio/pikachu2.mp3" autoplay type="audio/mpeg"/>
</audio>`;
}
function meowthSong() {
  sound.innerHTML = `<audio autoplay class="display-none ">
<source src="./media/audio/meowth_song.mp3" autoplay type="audio/mpeg"/>
</audio>`;
}
function chanseySong() {
  sound.innerHTML = `<audio autoplay class="display-none ">
  <source src="./media/audio/chansey.mp3" autoplay type="audio/mpeg"/>
  </audio>`;
}
